### Loading Data

In [31]:
import pandas as pd
pd.set_option("display.max_columns", None)

df = pd.read_parquet(r"Finalproject.parquet")

In [32]:
df.shape

(9836, 546)

In [33]:
df

,Throws,xMLBAMID,Name,Team,Season,Age,AgeR,SeasonMin,SeasonMax,W,L,ERA,G,GS,QS,CG,ShO,SV,BS,IP,TBF,H,R,ER,HR,BB,IBB,HBP,WP,BK,SO,GB,FB,LD,IFFB,Pitches,Balls,Strikes,RS,IFH,BU,BUH,K/9,BB/9,K/BB,H/9,HR/9,AVG,WHIP,BABIP,LOB%,FIP,GB/FB,LD%,GB%,FB%,IFFB%,HR/FB,IFH%,BUH%,TTO%,CFraming,Starting,Start-IP,Relieving,Relief-IP,RAR,WAR,Dollars,RA9-Wins,LOB-Wins,BIP-Wins,BS-Wins,tERA,xFIP,WPA,-WPA,+WPA,RE24,REW,pLI,inLI,gmLI,exLI,Pulls,Games,WPA/LI,Clutch,FB%1,FBv,SL%,SLv,CT%,CTv,CB%,CBv,CH%,CHv,SF%,SFv,KN%,KNv,XX%,PO%,wFB,wSL,wCT,wCB,wCH,wSF,wKN,wFB/C,wSL/C,wCT/C,wCB/C,wCH/C,wSF/C,wKN/C,O-Swing%,Z-Swing%,Swing%,O-Contact%,Z-Contact%,Contact%,Zone%,F-Strike%,SwStr%,CStr%,C+SwStr%,HLD,SD,MD,ERA-,FIP-,xFIP-,K%,BB%,K-BB%,SIERA,kwERA,RS/9,E-F,Pull,Cent,Oppo,Soft,Med,Hard,bipCount,Pull%,Cent%,Oppo%,Soft%,Med%,Hard%,K/9+,BB/9+,K/BB+,H/9+,HR/9+,AVG+,WHIP+,BABIP+,LOB%+,K%+,BB%+,LD%+,GB%+,FB%+,HRFB%+,Pull%+,Cent%+,Oppo%+,Soft%+,Med%+,Hard%+,xERA,pb_o_CH,pb_s_CH,pb_c_CH,pb_o_CU,pb_s_CU,pb_c_CU,pb_o_FF,pb_s_FF,pb_c_FF,pb_o_SI,pb_s_SI,pb_c_SI,pb_o_SL,pb_s_SL,pb_c_SL,pb_o_KC,pb_s_KC,pb_c_KC,pb_o_FC,pb_s_FC,pb_c_FC,pb_o_FS,pb_s_FS,pb_c_FS,pb_overall,pb_stuff,pb_command,pb_xRV100,pb_ERA,sp_s_CH,sp_l_CH,sp_p_CH,sp_s_CU,sp_l_CU,sp_p_CU,sp_s_FF,sp_l_FF,sp_p_FF,sp_s_SI,sp_l_SI,sp_p_SI,sp_s_SL,sp_l_SL,sp_p_SL,sp_s_KC,sp_l_KC,sp_p_KC,sp_s_FC,sp_l_FC,sp_p_FC,sp_s_FS,sp_l_FS,sp_p_FS,sp_s_FO,sp_l_FO,sp_p_FO,sp_stuff,sp_location,sp_pitching,PPTV,CPTV,BPTV,DSV,DGV,BTV,rPPTV,rCPTV,rBPTV,rDSV,rDGV,rBTV,EBV,ESV,rFTeamV,rBTeamV,rTV,BReview,BOverturned,BCorrect%,wBReview,PReview,POverturned,PCorrect%,wPReview,CReview,COverturned,CCorrect%,wCReview,pfxFA%,pfxFT%,pfxFC%,pfxFS%,pfxFO%,pfxSI%,pfxSL%,pfxCU%,pfxKC%,pfxEP%,pfxCH%,pfxSC%,pfxKN%,pfxUN%,pfxSLO%,pfxST%,pfxCUO%,pfxCV%,pfxvFA,pfxvFT,pfxvFC,pfxvFS,pfxvFO,pfxvSI,pfxvSL,pfxvCU,pfxvKC,pfxvEP,pfxvCH,pfxvSC,pfxvKN,pfxvSLO,pfxvST,pfxvCUO,pfxvCV,pfxFA-X,pfxFT-X,pfxFC-X,pfxFS-X,pfxFO-X,pfxSI-X,pfxSL-X,pfxCU-X,pfxKC-X,pfxEP-X,pfxCH-X,pfxSC-X,pfxKN-X,pfxSLO-X,pfxST-X,pfxCUO-X,pfxCV-X,pfxFA-Z,pfxFT-Z,pfxFC-Z,pfxFS-Z,pfxFO-Z,pfxSI-Z,pfxSL-Z,pfxCU-Z,pfxKC-Z,pfxEP-Z,pfxCH-Z,pfxSC-Z,pfxKN-Z,pfxSLO-Z,pfxST-Z,pfxCUO-Z,pfxCV-Z,pfxwFA,pfxwFT,pfxwFC,pfxwFS,pfxwFO,pfxwSI,pfxwSL,pfxwCU,pfxwKC,pfxwEP,pfxwCH,pfxwSC,pfxwKN,pfxwSLO,pfxwST,pfxwCUO,pfxwCV,pfxwFA/C,pfxwFT/C,pfxwFC/C,pfxwFS/C,pfxwFO/C,pfxwSI/C,pfxwSL/C,pfxwCU/C,pfxwKC/C,pfxwEP/C,pfxwCH/C,pfxwSC/C,pfxwKN/C,pfxwSLO/C,pfxwST/C,pfxwCUO/C,pfxwCV/C,pfxaaFA,pfxaaFT,pfxaaFC,pfxaaFS,pfxaaFO,pfxaaSI,pfxaaSL,pfxaaCU,pfxaaKC,pfxaaEP,pfxaaCH,pfxaaSC,pfxaaKN,pfxaaSLO,pfxaaST,pfxaaCUO,pfxaaCV,pfxspFA,pfxspFT,pfxspFC,pfxspFS,pfxspFO,pfxspSI,pfxspSL,pfxspCU,pfxspKC,pfxspEP,pfxspCH,pfxspSC,pfxspKN,pfxspSLO,pfxspST,pfxspCUO,pfxspCV,pfxO-Swing%,pfxZ-Swing%,pfxSwing%,pfxO-Contact%,pfxZ-Contact%,pfxContact%,pfxZone%,pfxPace,AvgBatSpeed,FastSwing%,SwingLength,SquaredUpContact%,SquaredUpSwing%,BlastContact%,BlastSwing%,Swords,CompetitiveSwings,Tilt,AttackAngle,AttackDirection,IdealAttackAngle%,DepthInBox,DistanceOffPlate,scH-Swing%,scH-Contact%,scH-Zone%,scS-Swing%,scS-Contact%,scS-Zone%,scC-Swing%,scC-Contact%,scC-Zone%,scW-Swing%,scW-Contact%,scW-Zone%,scSI-Swing%,scSI-Contact%,scSI-Zone%,scSO-Swing%,scSO-Contact%,scSO-Zone%,scO-Swing%,scO-Contact%,scO-Zone%,scZ-Swing%,scZ-Contact%,scZ-Zone%,piCH%,piCS%,piCU%,piFA%,piFC%,piFS%,piKN%,piSB%,piSI%,piSL%,piXX%,pivCH,pivCS,pivCU,pivFA,pivFC,pivFS,pivKN,pivSB,pivSI,pivSL,pivXX,piCH-X,piCS-X,piCU-X,piFA-X,piFC-X,piFS-X,piKN-X,piSB-X,piSI-X,piSL-X,piXX-X,piCH-Z,piCS-Z,piCU-Z,piFA-Z,piFC-Z,piFS-Z,piKN-Z,piSB-Z,piSI-Z,piSL-Z,piXX-Z,piwCH,piwCS,piwCU,piwFA,piwFC,piwFS,piwKN,piwSB,piwSI,piwSL,piwXX,piwCH/C,piwCS/C,piwCU/C,piwFA/C,piwFC/C,piwFS/C,piwKN/C,piwSB/C,piwSI/C,piwSL/C,piwXX/C,piO-Swing%,piZ-Swing%,piSwing%,piO-Contact%,piZ-Contact%,piContact%,piZone%,piPace,Events,EV,LA,Barrels,Barrel%,maxEV,HardHit,HardHit%,Q,TG,TIP,PlayerNameRoute,PlayerName,positionDB,position,TeamName,TeamNameAbb,teamid,playerTeamId,playerid,EV90,fg_playerid,fg_teamid
0,L,477132,"<a href=""statss.aspx?playerid=2036&position=P""...","<a href=""leaders.aspx?pos=all&stats=pit&lg=all...",2015,27.0,27 - 27,2015,2015,16.0,7.0,2.127507,33.0,33.0,27.0,4.0,3.0,0.0,0.0,232.2,890.0,163.0,62.0,55.0,15.0,42.0,1.0,5.0,9.0,3.0,301.0,262.0,148.0,114.0,14.0,3392.0,1089.0,2303.0,115.0,16.0,18.0,4.0,11.643266,1.624642,7.166667,6.305157,0.580229,0.193357,0.881089,0.280835,0.783069,1.990327,1.770270,0.217557,0.500000,0.282443,0.094595,0.101351,0.061069,0.222222,0.402247,-0.11,70.770294,232.199997,NaN,NaN,70.770294,8.552693,68.421547,8.145162,-1.405175,0.997644,-0.407531,2.283441,2.090899,4.978272,-11.319584,16.297855,46.052299,5.209179,0.957877,0.946983,0.878879,1.137317,29.0,33.0,5.665493,-0.468300,0.538802,93.620671,0.275302,88.075188,NaN,NaN,0.181469,73.552117,0.004426,87.533333,NaN,NaN,NaN,NaN,0.000884,None,24.695097,15.712569,NaN,16.441906,-1.157094,NaN,NaN,1.352415,1.684091,NaN,2.673481,-7.713957,NaN,NaN,0.344489,0.686594,0.511655,0.512563,0.781882,0.689158,0.488640,0.682022,0.158903,0.164210,0.323113,0.0,0.0,0.0,56.955890,52.634069,54.204499,0.338202,0.047191,0.291011,2.234750,1.997074,4.448424,0.137180,218.0,206.0,118.0,108.0,297.0,137.0,542.0,0.402214,0.380074,0.217712,0.199262,0.547970,0.252768,147.665754,55.112463,267.935297,72.124487,59.441895,77.035704,67.834536,93.907921,107.225323,163.426196,60.994648,103.164299,108.072751,86.515623,89.249441,106.003838,106.307796,82.766289,107.637250,105.056505,86.186303,2.128946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.535303,None,NaN,NaN,NaN,0.001182,0.278582,0.181684,NaN,NaN,0.003250,NaN,NaN,NaN,0.278582,NaN,0.181684,NaN,93.577099,None,NaN,NaN,NaN,93.525002,88.038491,73.501791,NaN,NaN,87.699996,NaN,NaN,88.038491,NaN,73.501791,NaN,0.914953,None,NaN,NaN,NaN,5.932500,-2.186158,-1.063018,NaN,NaN,6.177272,NaN,NaN,-2.186158,NaN,-1.063018,NaN,11.102121,None,NaN,NaN,NaN,11.392500,3.425949,-10.171966,NaN,NaN,9.189091,NaN,NaN,3.425949,NaN,-10.171966,NaN,24.981564,None,NaN,NaN,NaN,0.075876,17.905991,17.450726,NaN,NaN,-0.730643,NaN,NaN,17.905991,NaN,17.450726,NaN,1.378673,None,NaN,NaN,NaN,1.896899,1.898833,2.837516,NaN,NaN,-6.642205,NaN,NaN,1.898833,NaN,2.837516,NaN,0.000000,None,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,2154.673841,None,NaN,NaN,NaN,2249.750000,1421.609756,2215.515447,NaN,NaN,1851.000000,NaN,NaN,1421.609756,NaN,2215.515447,NaN,0.338081,0.669492,0.511374,0.472527,0.789030,0.689197,0.522895,23.246893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.712810,0.817391,0.285967,0.548431,0.681592,0.433087,0.295014,0.380282,0.213294,0.104803,0.000000,0.067651,0.629492,0.718504,0.238405,0.449165,0.618243,0.194682,0.331056,0.495310,0.475628,0.674930,0.775459,0.524372,0.004422,NaN,0.180425,0.536262,NaN,NaN,NaN,NaN,NaN,0.275059,NaN,88.345011,NaN,73.937040,94.138185,NaN,NaN,NaN,NaN,NaN,88.482357,NaN,5.510494,NaN,-1.359068,0.467369,NaN,NaN,NaN,NaN,NaN,-2.788811,NaN,8.399701,NaN,-11.156182,10.513805,NaN,NaN,NaN,NaN,NaN,2.518557,NaN,-0.745692,NaN,16.444525,27.243383,NaN,NaN,NaN,NaN,NaN,16.787548,NaN,-4.971278,NaN,2.687014,1.497712,NaN,NaN,NaN,NaN,NaN,1.799308,NaN,0.340149,0.667607,0.511518,0.471767,0.790363,0.689376,0.523331,23.246893,542.0,85.606419,8.861868,18.0,0.033210,113.3,133.0,0.245387,1.43621,162.0,232.666672,Clayton Kershaw,Clayton Kershaw,P,P,LAD,LAD,22,-1.0,2036,102.4,2036,22
1,R,453562,"<a href=""statss.aspx?playerid=4153&position=P""...","<a href=""leaders.aspx?pos=all&stats=pit&lg=all...",2015,29.0,29 - 29,2015,2015,22.0,6.0,1.768559,33.0,33.0,29.0,4.0,3.0,0.0,0.0,229.0,870.0,150.0,52.0,45.0,10.0,48.0,2.0,6.0,6.0,0.0,236.0,318.0,129.0,119.0,12.0,3438.0,1202.0,2236.0,118.0,22.0,14.0,3.0,9.275109,1.886463,4.916667,5.895196,0.393013,0.183824,0.864629,0.245614,0.800000,2.347568,2.465116,0.210247,0.561837,0.227915,0.093023,0.077519,0.069182,0.214286,0.337931,2.22,59.980686,229.000000,NaN,NaN,59.980686,7.033605,56.268841,9.353845,-0.569762,2.890002,2.320240,2.768426,2.611157,5.929730,-9.862086,15.791816,56.133999,6.044352,0.919490,0.918133,0.874109,0.833200,29.0,33.0,5.778588,0.670347,0.506997,94.609447,NaN,NaN,0.291254,90.313627,0.154227,80.710775,0.047522,89.000000,NaN,NaN,NaN,NaN,0.002327,None,23.673140,NaN,23.467541,7.664321,2.834517,NaN,NaN,1.361308,NaN,2.349103,1.448832,1.738967,NaN,NaN,0.342201,0.629874,0.469096,0.612805,0.866737,0.763207,0.441108,0.602299,0.110820,0.176556,0.287376,0.0,0.0,0.0,45.028216,60.561019,67.506423,0.271264,0.055172,0.216092,2.745920,2.896105,4.637554,-0.579009,199.0,219.0,162.0,132.0,320.0,128.0,580.0,0.343103,0.377586,0.279310,0.227586,0.551724,0.220690,117.631589,63.994173,183.816076,67.434953,40.262436,73.237435,66.567287,82.130469,109.543709,131.080452,71.310655,99.697989,121.438639,69.813175,68.263138,90.425197,105.612008,106.183683,122.937411,105.776153,75.248690,2.358239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.180333,None,NaN,NaN,NaN,0.331193,0.288591,0.153487,NaN,NaN,0.046396,NaN,NaN,NaN,0.288591,NaN,0.153487,NaN,94.377509,None,NaN,NaN,NaN,94.651893,90.203638,80.653042,NaN,NaN,88.889304,NaN,NaN,90.203638,NaN,80.653042,NaN,-5.262929,None,NaN,NaN,NaN,-8.321366,2.885622,5.694829,NaN,NaN,-10.008742,NaN,NaN,2.885622,NaN,5.694829,NaN,8.811666,None,NaN,NaN,NaN,6.979533,2.593145,-9.149486,NaN,NaN,2.188994,NaN,NaN,2.593145,NaN,-9.149486,NaN,2.799101,None,NaN,NaN,NaN,22.486160,24.844395,7.581256,NaN,NaN,3.064698,NaN,NaN,24.844395,NaN,7.581256,NaN,0.452929,None,NaN,NaN,NaN,1.981159,2.512072,1.441303,NaN,NaN,1.927483,NaN,NaN,2.512072,NaN,1.441303,NaN,0.000000,None,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,2236.745955,None,NaN,NaN,NaN,2212.141850,1712.153691,2653.026616,NaN,NaN,1906.949686,NaN,NaN,1712.153691,NaN,2653.026616,NaN,0.314647,0.614253,0.469215,0.570881,0.853591,0.761816,0.515903,23.446228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.657366,0.893039,0.261453,0.536301,0.749681,0.426029,0.277062,0.497674,0.226437,0.071186,0.238095,0.086081,0.578470,0.807175,0.224978,0.489115,0.673590,0.201050,0.325568,0.591623,0.513569,0.620876,0.856039,0.486431,0.047203,NaN,0.153846,0.074592,0.000583,0.000291,NaN,NaN,0.430070,0.291958,NaN,89.462867,NaN,81.079190,94.794479,95.036499,95.717102,NaN,NaN,95.092575,90.642005,NaN,-9.046024,NaN,7.136599,-2.909671,-4.630005,-8.29333,NaN,NaN,-6.863398,4.032653,NaN,0.905721,NaN,-10.861853,7.953555,5.350630,7.53856,NaN,NaN,6.282587,1.576218,NaN,2.822798,NaN,7.418314,-0.692124,0.109129,-0.034922,NaN,NaN,24.996477,23.748367,NaN,1.742468,NaN,1.404984,-0.270361,5.456431,-3.492241,NaN,NaN,1.693528,2.370097,NaN,0.310006,0.613459,0.469215,0.570297,0.849501,0.761816,0.524657,23.446228,580.0,85.124552,4.353047,13.0,0.022414,111.5,143.0,0.246552,1.41358,162.0,229.000015,Jake Arrieta,Jake Arrieta,P,P,CHC,CHC,17,-1.0,4153,101.6,4153,17
2,L,456034,"<a href=""statss.aspx?playerid=3184&position=P""...",- - -,2015,29.0,29 - 29,2015,2015,18.0,5.0,2.450832,32.0,32.0,24.0,3.0,1.0,0.0,0.0,220.1,888.0,190.0,70.0,60.0,17.0,47.0,2.0,3.0,4.0,0.0,225.0,243.0,219.0,139.0,24.0,3388.0,1066.0,2322.0,137.0,17.0,12.0,3.0,9.190620,1.919818,4.787234,7.760968,0.694402,0.226730,1.075643,0.290268,0.786309,2.775046,1.109589,0.231281,0.404326,0.364393,0.109589,0.077626,0.069959,0.250000,0.325450,-1.87,58.253067,220.099998,NaN,NaN,58.253067,6.698485,53.587883,7.164915,0.238597,0.227833,0.466430,3.360430,3.238764,3.697698,-12.695616,16.393314,36.418600,3.796465,0.983666,0.927653,0.854706,1.240028,29.0,32.0,3.412162,0.346937,0.533946,94.164994,NaN,NaN,0.159205,89.620112,0.080344,79.674074,0.226505,85.226440,NaN,NaN,NaN,NaN,0.004427,None,19.687125,NaN,-0.470455,1.538639,10.523867,NaN,NaN,1.093122,NaN,-0.087608,0.567764,1.377469,NaN,NaN,0.338738,0.685905,0.508153,0.666667,0.816652,0.765461,0.487993,0.670045,0.118654,0.175030,0.293684,0.0,0.0,0.0,60.126124,67.450683,79.991049,0.253378,0.052928,0.200450,3.267244,3.083803,5.596066,-0.324214,204.0,225.0,184.0,104.0,336.0,173.0,613.0,0.332790,0.367047,0.300163,0.169657,0.548124,0.282219,120.250869,66.480194,180.882253,89.020547,65.538135,90.544315,83.412049,98.972093,107.929831,126.123922,69.727088,111.626532,91.170413,104.313636,68.410195,82.627659,105.748966,119.993788,90.415379,103.604499,99.617032,3.185838,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.349911,None,0.131735,NaN,NaN,0.211664,NaN,NaN,0.080817,NaN,0.225873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.928594,None,89.070339,NaN,NaN,94.113145,NaN,NaN,79.589008,NaN,85.185324,NaN,NaN,NaN,NaN,NaN,NaN,6.540338,None,0.218045,NaN,NaN,9.571132,NaN,NaN,-5.557693,NaN,10.448794,NaN,NaN,NaN,NaN,NaN,NaN,10.094848,None,5.051775,NaN,NaN,8.276727,NaN,NaN,-0.644762,NaN,5.863945,NaN,NaN,NaN,NaN,NaN,NaN,7.957268,None,1.483377,NaN,NaN,10.625118,NaN,NaN,1.833777,NaN,12.427280,NaN,NaN,NaN,NaN,NaN,NaN,0.673204,None,0.333343,NaN,NaN,1.486030,NaN,NaN,0.671713,NaN,1.628739,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,None,0.000000,NaN,NaN,0.000000,NaN,NaN,0.0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,2232.296954,None,2059.393258,NaN,NaN,2177.748252,NaN,NaN,1939.754579,NaN,1956.749672,NaN,NaN,NaN,NaN,NaN,NaN,0.302881,0.656266,0.507401,0.607889,0.817615,0.764877,0.578745,26.639632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.724365,0.837662,0.314683,0.519839,0.736093,0.440201,0.243976,0.586420,0.196566,0.054878,0.222222,0.048549,0.599506,0.767010,0.239491,0.424779,0.684028,0.200710,0.304781,0.640523,0.445826,0.670406,0.810359,0.554174,0.226627,NaN,0.080178,0.293491,0.163609,NaN,NaN,NaN,0.235207,NaN,NaN,85.758996,NaN,80.175843,94.980483,90.052296,NaN,NaN,NaN,94.743797,NaN,NaN,9.916189,NaN,-6.520743,6.301191,0.111782,NaN,NaN,NaN,8.575502,NaN,NaN,4.167894,NaN,-2.527805,8.847955,4.089572,NaN,NaN,NaN,7.440789,NaN,NaN,11.356968,NaN,1.741288,6.066668,0.707822,NaN,NaN,NaN,13.933266,NaN,NaN,1.482633,NaN,0.642542,0.611559,0.127997,NaN,NaN,NaN,1.752612,NaN,NaN,0.303331,0.653787,0.507401,0.598131,0.820373,0.764877,0.582297,26.639632,613.0,87.411339,12.683587,28.0,0.045677,114.7,189.0,0.308320,1.36429,161.5,220.333344,David Price,David Price,P,P,- - -,2 Tms,0,-1.0,3184,103.9,3184,NaN
3,R,453286,"<a href=""statss.aspx?playerid=3137&position=P""...","<a href=""leaders.aspx?pos=all&stats=pit&lg=all...",2015,30.0,30 - 30,2015,2015,14.0,12.0,2.794460,33.0,33.0,23.0,4.0,3.0,0.0,0.0,228.2,899.0,176.0,74.0,71.0,27.0,34.0,2.0,5.0,10.0,1.0,276.0,202.0,256.0,106.0,33.0,3359.0,979.0,2380.0,104.0,10.0,20.0,3.0,10.862973,1.338192,8.117647,6.927113,1.062682,0.204651,0.918367,0.267504,0.795711,2.766247,0.789062,0.187943,0.358156,0.453901,0.128906,0.105469,0.049505,0.150000,0.374861,-0.89,56.159695,228.199997,NaN,NaN,56.159695,6.515219,52.121754,6.833667,-1.315803,1.634251,0.318448,2.808446,2.883328,3.248440,-13.238872,16.487312,35.840801,3.818711,0.957373,0.967385,0.868703,1.151421,29.0,33.0,3.954099,-0.561023,0.593797,94.167674,0.187593,86.195860,0.005667,89.526316,0.081121,79.558824,0.131822,84.871041,NaN,NaN,NaN,NaN,0.001786,None,20.927141,12.339174,-0.247681,-0.162504,3.000859,NaN,NaN,1.051087,1.961713,-1.303587,-0.059744,0.678927,NaN,NaN,0.360000,0.734803,0.547569,0.580431,0.789132,0.720588,0.500447,0.713014,0.152724,0.156892,0.309616,0.0,0.0,0.0,70.922140,72.320504,74.465282,0.307008,0.037820,0.269188,2.625781,2.258953,4.093294,0.028214,219.0,196.0,169.0,122.0,298.0,164.0,584.0,0.375000,0.335616,0.289384,0.208904,0.510274,0.280822,137.769681,45.395283,303.488955,79.239017,108.867043,81.535407,70.704584,89.450382,108.956426,148.352399,48.882304,89.121529,77.413814,139.035266,92.875200,98.831560,93.872936,110.013155,112.845724,97.829358,95.752026,2.609091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.592902,None,0.016403,NaN,NaN,NaN,0.178646,0.080823,NaN,NaN,0.131226,NaN,NaN,NaN,0.178646,NaN,0.080823,NaN,94.123994,None,89.289089,NaN,NaN,NaN,85.969285,79.483027,NaN,NaN,84.821138,NaN,NaN,85.969285,NaN,79.483027,NaN,-8.116972,None,-2.565455,NaN,NaN,NaN,0.458595,3.257343,NaN,NaN,-9.048955,NaN,NaN,0.458595,NaN,3.257343,NaN,7.795724,None,3.165818,NaN,NaN,NaN,1.309744,-2.342620,NaN,NaN,1.330773,NaN,NaN,1.309744,NaN,-2.342620,NaN,22.394676,None,0.088036,NaN,NaN,NaN,11.824952,-0.249364,NaN,NaN,4.783796,NaN,NaN,11.824952,NaN,-0.249364,NaN,1.126493,None,0.160066,NaN,NaN,NaN,1.974116,-0.092016,NaN,NaN,1.087226,NaN,NaN,1.974116,NaN,-0.092016,NaN,0.000000,None,0.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,0.000000,NaN,2449.181087,None,1917.109091,NaN,NaN,NaN,1758.353923,1753.191882,NaN,NaN,1443.838636,NaN,NaN,1758.353923,NaN,1753.191882,NaN,0.335461,0.702007,0.547868,0.547569,0.781525,0.721285,0.579481,21.988579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.761726,0.806650,0.318019,0.599567,0.705174,0.413484,0.283721,0.453552,0.192422,0.043137,0.090909,0.076074,0.663291,0.732824,0.235680,0.515101,0.657980,0.177804,0.334669,0.570858,0.446466,0.719828,0.777695,0.553534,0.130991,NaN,0.082465,0.590950,0.009527,NaN,NaN,NaN,NaN,0.182495,NaN,85.364276,NaN,80.094497,94.749284,90.194046,NaN,NaN,NaN,NaN,86.513006,NaN,-8.292772,NaN,4.162534,-7.185955,-1.536665,NaN,NaN,NaN,NaN,1.409020,NaN,0.241743,NaN,-3.380343,7.056930,2.395938,NaN,NaN,NaN,NaN,0.423328,NaN,4.482637,NaN,-1.725183,24.107061,0.606117,NaN,NaN,NaN,NaN,12.103803,NaN,1.018781,NaN,-0.622810,1.214462,1.894117,NaN,NaN,NaN,NaN,1.974519,NaN,0.331416,0.701683,0.548031,0.540130,0.781977,0.721285,0.585024,21.988579,584.0,87.062542,17.120072,34.0,0.058219,114.7,174.0,0.297945,1.41152,162.0,228.666687,Max Scherzer,Max Scherzer,P,P,WSN,WSN,24,14.0,3137,103.5,3137,24

### Selecting Columns of Interest

In [34]:
cols = [
    #who/when
    "PlayerName", "position", "Throws", "Season", "Age",
    #workload
    "IP", "GS",
    #results
    "ERA", "FIP", "WHIP", "SO", "K%", "BB%",
    #value
    "WAR", "Dollars",
    #fastball velocity
    "FBv",
    #contact quality allowed
    "HardHit%", "Barrel%",
]

missing = [c for c in cols if c not in df.columns]
print("Not found:", missing)

variables = df[cols].copy()
print(variables.shape)
variables.head()

Not found: []
(9836, 18)

,PlayerName,position,Throws,Season,Age,IP,GS,ERA,FIP,WHIP,SO,K%,BB%,WAR,Dollars,FBv,HardHit%,Barrel%
0,Clayton Kershaw,P,L,2015,27.0,232.2,33.0,2.127507,1.990327,0.881089,301.0,0.338202,0.047191,8.552693,68.421547,93.620671,0.245387,0.033210
1,Jake Arrieta,P,R,2015,29.0,229.0,33.0,1.768559,2.347568,0.864629,236.0,0.271264,0.055172,7.033605,56.268841,94.609447,0.246552,0.022414
2,David Price,P,L,2015,29.0,220.1,32.0,2.450832,2.775046,1.075643,225.0,0.253378,0.052928,6.698485,53.587883,94.164994,0.308320,0.045677
3,Max Scherzer,P,R,2015,30.0,228.2,33.0,2.794460,2.766247,0.918367,276.0,0.307008,0.037820,6.515219,52.121754,94.167674,0.297945,0.058219
4,Dallas Keuchel,P,L,2015,27.0,232.0,33.0,2.482758,2.909456,1.017241,216.0,0.237102,0.055982,5.693698,45.549583,89.601132,0.280374,0.032710

### Cleaning the Data

Filtering

In [35]:
#This data looks at anyone who has thrown a pitch. Due to this, the data needs to be filtered to only true pitchers. 
#This will get rid of position players who came in and threw for 1 inning
variables = variables[variables.position == 'P']

Checking summary stats for games started and innings pitched

In [36]:
variables.GS.describe()

count    9261.000000
mean        5.952921
std         9.892115
min         0.000000
25%         0.000000
50%         0.000000
75%         8.000000
max        35.000000
Name: GS, dtype: float64

In [37]:
variables.IP.describe()

count    9261.000000
mean       52.544596
std        50.876583
min         0.000000
25%        13.200000
50%        37.200000
75%        68.100000
max       232.200000
Name: IP, dtype: float64

In [38]:
#Given that Tarik Skubal is a starter, we want to make sure we are only looking at starters and not relievers
#as they receive vastly different contracts. In addition, we want to make sure we are getting close to a season's worth
#of pitching for a starter as opposed to having seasons in which a starter only made 8 starts and then got hurt. 
#Any row that was from the 2020 season will also be dropped from our data for a similar reason as there were only 60 games
#that year and each pitcher made at most a handful of starts.
variables = variables[
    (variables["position"] == "P")
    & (variables["Season"] != 2020)
    & (variables["GS"] >= 25)
    & (variables["IP"] >= 130)
].copy()

print(variables.shape)
#We have roughly an equal amount of pitching rows from each year
print(variables["Season"].value_counts().sort_index())

(928, 18)
Season
2015    93
2016    92
2017    91
2018    89
2019    87
2021    71
2022    79
2023    76
2024    86
2025    83
2026    81
Name: count, dtype: int64

In [39]:
#Now that the data is starters who pitched roughly a full season, we can begin to inspect the data for any NAs
variables.isna().sum().sort_values(ascending=False)

PlayerName    0
position      0
HardHit%      0
FBv           0
Dollars       0
WAR           0
BB%           0
K%            0
SO            0
WHIP          0
FIP           0
ERA           0
GS            0
IP            0
Age           0
Season        0
Throws        0
Barrel%       0
dtype: int64

In [40]:
#There are no NAs for any of the selected columns, so the data is now clean.

### Creating Summary Stats Table

In [41]:
num_cols = ["Age", "IP", "GS", "ERA", "FIP", "WHIP", "SO", "K%", "BB%",
            "WAR", "Dollars", "FBv", "HardHit%", "Barrel%"]

summary = variables[num_cols].describe().T[["count", "mean", "std", "min", "50%", "max"]]
summary = summary.rename(columns={"50%": "median"}).round(2)
summary

          count    mean    std     min  median     max
Age       928.0   29.04   3.83   21.00   29.00   44.00
IP        928.0  171.71  21.47  130.00  172.00  232.20
GS        928.0   29.89   2.47   25.00   30.00   35.00
ERA       928.0    3.92   0.85    1.66    3.88    6.81
FIP       928.0    4.00   0.72    1.63    3.99    6.45
WHIP      928.0    1.24   0.16    0.80    1.24    1.73
SO        928.0  161.66  39.94   73.00  155.00  326.00
K%        928.0    0.22   0.05    0.11    0.22    0.40
BB%       928.0    0.07   0.02    0.02    0.07    0.13
WAR       928.0    2.70   1.55   -1.01    2.53    9.04
Dollars   928.0   21.58  12.36   -8.09   20.24   72.33
FBv       928.0   92.94   2.42   81.49   92.92  100.63
HardHit%  928.0    0.37   0.04    0.25    0.37    0.50
Barrel%   928.0    0.07   0.02    0.02    0.07    0.14

In [43]:
#Saving data as a CSV
variables.to_csv("variables.csv", index=False)